apiVersion: v1
kind: Service
metadata:
  name: developer-productivity-frontend
  labels:
    app: developer-productivity-frontend
spec:
  type: LoadBalancer
  selector:
    app: developer-productivity-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
